version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nextjs_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mynextjsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mynextjsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
       - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: